### ISSUE TITLE
Index unit test fails, local/Test/Test minor bug can be seen

### ISSUE THREAD

**Issue by bojakowsky** [bojakowsky/TaskVlopper#8]
- Index unit test fails,
- After opening local/Test/Test site and then opening Log in / Register pop up, some reflection of those can be seen for couple of seconds on the bottom left of the site 
  ![bug](https://cloud.githubusercontent.com/assets/7606267/11543271/01be7be4-993c-11e5-8e57-3c155cb77351.png)

**Comment by mszynka** [comment]
@bojakowsky why reopen?

**Comment by bojakowsky** [comment]
Unit test has been written badly.
Explanation: Handling exception is faking unit test result - User is null, so to test it properly, we're going to fake User, i'm nearly done doing it, i'll commit in a second

**Comment by mszynka** [comment]
Ah. Ok then. I didn't knew how to fake User.

**Comment by bojakowsky** [comment]
Answer can be found: 
https://github.com/bojakowsky/TaskVlopper/pull/11

**Comment by mszynka** [comment]
@bojakowsky As you can see you don't need to comment where the answer was if you have referenced it in PR e.g. ;)
